### ISSUE TITLE
data loader failing to load elasticsearch

### ISSUE THREAD

**Issue by petehanssens** [stemma-ai/amundsen-custom#4] opened 2021-03-15 06:34 UTC
Here's the stacktrace:
`python3 example/scripts/sample_data_loader.py
WARNING:elasticsearch:PUT http://localhost:9200/table_fdc660f6-d25d-49b0-900f-3e2e598d0004 [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 232, in perform_request
    response = self.pool.urlopen(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11c7ad1f0>: Failed to establish a new connection: [Errno 61] Connection refused
WARNING:elasticsearch:PUT http://localhost:9200/table_fdc660f6-d25d-49b0-900f-3e2e598d0004 [status:N/A request:0.003s]
Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 232, in perform_request
    response = self.pool.urlopen(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11c7ad400>: Failed to establish a new connection: [Errno 61] Connection refused
WARNING:elasticsearch:PUT http://localhost:9200/table_fdc660f6-d25d-49b0-900f-3e2e598d0004 [status:N/A request:0.002s]
Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 232, in perform_request
    response = self.pool.urlopen(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11c7be820>: Failed to establish a new connection: [Errno 61] Connection refused
WARNING:elasticsearch:PUT http://localhost:9200/table_fdc660f6-d25d-49b0-900f-3e2e598d0004 [status:N/A request:0.003s]
Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 232, in perform_request
    response = self.pool.urlopen(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11c7befd0>: Failed to establish a new connection: [Errno 61] Connection refused
Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 159, in _new_conn
    conn = connection.create_connection(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 84, in create_connection
    raise err
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/connection.py", line 74, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 232, in perform_request
    response = self.pool.urlopen(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 726, in urlopen
    retries = retries.increment(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/util/retry.py", line 386, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/packages/six.py", line 735, in reraise
    raise value
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 670, in urlopen
    httplib_response = self._make_request(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connectionpool.py", line 392, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1255, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1301, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1250, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 1010, in _send_output
    self.send(msg)
  File "/usr/local/Cellar/python@3.8/3.8.8_1/Frameworks/Python.framework/Versions/3.8/lib/python3.8/http/client.py", line 950, in send
    self.connect()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 187, in connect
    conn = self._new_conn()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/urllib3/connection.py", line 171, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x11c7befd0>: Failed to establish a new connection: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "example/scripts/sample_data_loader.py", line 349, in <module>
    job_es_table.launch()
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/amundsen_databuilder-4.1.0-py3.8.egg/databuilder/job/job.py", line 76, in launch
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/amundsen_databuilder-4.1.0-py3.8.egg/databuilder/job/job.py", line 72, in launch
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/amundsen_databuilder-4.1.0-py3.8.egg/databuilder/publisher/base_publisher.py", line 40, in publish
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/amundsen_databuilder-4.1.0-py3.8.egg/databuilder/publisher/base_publisher.py", line 37, in publish
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/amundsen_databuilder-4.1.0-py3.8.egg/databuilder/publisher/elasticsearch_publisher.py", line 93, in publish_impl
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/elasticsearch/client/utils.py", line 101, in _wrapped
    return func(*args, params=params, **kwargs)
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/elasticsearch/client/indices.py", line 123, in create
    return self.transport.perform_request(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/elasticsearch/transport.py", line 402, in perform_request
    status, headers_response, data = connection.perform_request(
  File "/Users/peter/cloudshuttle/projects/amundsen-custom/databuilder/upstream/venv/lib/python3.8/site-packages/elasticsearch/connection/http_urllib3.py", line 245, in perform_request
    raise ConnectionError("N/A", str(e), e)
elasticsearch.exceptions.ConnectionError: ConnectionError(<urllib3.connection.HTTPConnection object at 0x11c7befd0>: Failed to establish a new connection: [Errno 61] Connection refused) caused by: NewConnectionError(<urllib3.connection.HTTPConnection object at 0x11c7befd0>: Failed to establish a new connection: [Errno 61] Connection refused)`

**Comment by dorianj** [comment] 2021-03-16 05:06
Closing as a dupe of https://github.com/stemma-ai/amundsen-custom/issues/3, I'm pretty sure they're same root cause

**Closed by dorianj** 2021-03-16 05:06 UTC
